import { useMemo, useState } from 'react';
import { BookOpen } from 'lucide-react';
import { Empty, External, Importer, JsonView, Notice, PageTitle, SaveButton, SearchForm, Source, ExportButton } from '../components/common';
import { api, useData, useTask, useMemoryState, type Row } from '../lib/api';
export default function Catalogue({ config, onSave, onRefresh }: { config: Row | null; onSave: () => void; onRefresh: () => void }) {
  const imported = useData<Row[]>('/records/catalogue', []), task = useTask('catalogue'); const [query, setQuery] = useMemoryState('catalogue:query', ''), [jurisdiction, setJurisdiction] = useMemoryState('catalogue:jurisdiction', 'All jurisdictions'), [category, setCategory] = useMemoryState('catalogue:category', 'All categories');
  const registries = config?.registries || [];
  const directory = registries.filter((r: Row) => (jurisdiction === 'All jurisdictions' || r.jurisdiction === jurisdiction) && (category === 'All categories' || r.category === category));
  const jurisdictions = [...new Set<string>(registries.map((r: Row) => r.jurisdiction))].sort(), categories = [...new Set<string>(registries.map((r: Row) => r.category))].sort();
  const records = useMemo(() => { const rows = [...(task.data?.records || []), ...imported.data.filter(r => query && `${r.title} ${r.identifier}`.toLowerCase().includes(query.toLowerCase()))]; const unique = new Map(rows.map(r => [`${r.source}:${r.identifier}`, r])); return [...unique.values()] as Row[]; }, [task.data, imported.data, query]);
  const link = (url: string) => url.replace(/\{q\}|%7Bq%7D/gi, encodeURIComponent(query));
  return <><PageTitle title="Catalogue" description="Search entity records, review official registries, and preserve strong identifiers." actions={<><Importer module="catalogue" label="Import records" onImport={imported.refresh} /><Importer module="registry" label="Add sources" onImport={onRefresh} /></>} /><SearchForm cacheKey="catalogue:input" label="Registry search name" placeholder="Company name or imported record identifier" busy={task.busy} button="Search records" onSubmit={value => { setQuery(value); void task.run(() => api('/catalogue', { query: value })); }} />{(task.error || imported.error) && <Notice tone="error">{task.error || imported.error}</Notice>}{task.data && <><div className="result-summary"><span><BookOpen size={18} /><strong>{records.length} records returned</strong> for “{query}”</span><ExportButton filename="registry-records.json" value={records} /><SaveButton key={`${task.data.retrievedAt}-${query}`} module="catalogue" title={`Public record search · ${query}`} source="GLEIF / imported records" payload={{ query, results: records, provider: task.data, manualSources: directory.map((r: Row) => ({ name: r.name, url: link(r.url), status: r.access === 'api' && r.name.startsWith('GLEIF') ? task.data?.status : 'not_searched' })) }} onSave={onSave} /></div>{task.data.status === 'unavailable' && <Notice tone="warning">GLEIF was unavailable: {task.data.error}. Manual registries have not been searched.</Notice>}<Notice>Only GLEIF's LEI API and your imports are searched automatically. Other registries require manual review. A same-name result is not an identity match.</Notice>{records.length ? <div className="record-list">{records.map((r: Row) => <article key={`${r.source}-${r.identifier}`}><div className="row between wrap"><h2>{r.title}</h2><span className="tag">{r.jurisdiction || 'Jurisdiction not supplied'}</span></div><code>{r.identifier}</code><Source name={r.source} url={r.url} retrievedAt={r.importedAt || task.data?.retrievedAt} />{r.details && <details><summary>Published record</summary><JsonView value={r.details} /></details>}<SaveButton module="catalogue" title={r.title} source={r.source} payload={r} onSave={onSave} /></article>)}</div> : <Empty title="No records returned from searched sources">Review the manual registries below or import records from a source you can access.</Empty>}</>}
    <section className="standalone-panel"><div className="row between wrap"><h2>Registry directory <span className="count">{directory.length}</span></h2><div className="row wrap"><select aria-label="Registry jurisdiction" value={jurisdiction} onChange={e => setJurisdiction(e.target.value)}><option>All jurisdictions</option>{jurisdictions.map(j => <option key={j}>{j}</option>)}</select><select aria-label="Registry category" value={category} onChange={e => setCategory(e.target.value)}><option>All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div></div><p className="muted">{registries.length} curated or imported sources. “Manual review” means unsearched. Access may require fees, login, CAPTCHA, or jurisdiction-specific terms. Add your own sources to expand the directory.</p><div className="table-wrap"><table><thead><tr><th>Source</th><th>Jurisdiction</th><th>Records</th><th>Access</th></tr></thead><tbody>{directory.map((r: Row, i: number) => <tr key={i}><td><External href={link(r.url)}>{r.name}</External></td><td>{r.jurisdiction}</td><td>{r.category}</td><td><span className="tag">{r.name.startsWith('GLEIF') ? 'API + manual' : 'Manual review'}</span></td></tr>)}</tbody></table></div></section></>;
}
