import { useMemo, useState } from 'react';
import { GitBranch, Search, Plus, Minus, RotateCcw, X } from 'lucide-react';
import { Empty, External, Importer, Notice, PageTitle, SaveButton, Source, ExportButton } from '../components/common';
import { api, short, time, useData, useTask, useMemoryState, type Row } from '../lib/api';
function FlowGraph({ transfers, root, selected, onSelect }: { transfers: Row[]; root: string; selected: string; onSelect: (wallet: string) => void }) {
  const [zoom, setZoom] = useState(1);
  const nodes = useMemo(() => [...new Set([root, ...transfers.flatMap(t => [t.from, t.to])])].filter(Boolean).slice(0, 24), [transfers, root]);
  const positions = new Map(nodes.map((node, i) => [node, i === 0 ? { x: 400, y: 225 } : { x: 400 + Math.cos((i - 1) / Math.max(nodes.length - 1, 1) * Math.PI * 2) * 285, y: 225 + Math.sin((i - 1) / Math.max(nodes.length - 1, 1) * Math.PI * 2) * 155 }]));
  const center = zoom > 1 && positions.has(selected) ? positions.get(selected)! : { x: 400, y: 225 };
  return <div className="flow-canvas"><div className="row between"><span className="muted">Select a wallet to inspect its connections</span><div className="segmented"><button aria-label="Zoom graph in" onClick={() => setZoom(z => Math.min(2.5, z * 1.25))}><Plus size={15} /></button><button aria-label="Zoom graph out" onClick={() => setZoom(z => Math.max(.7, z / 1.25))}><Minus size={15} /></button><button aria-label="Reset graph zoom" onClick={() => setZoom(1)}><RotateCcw size={15} /></button></div></div><svg viewBox={`${center.x - 400 / zoom} ${center.y - 225 / zoom} ${800 / zoom} ${450 / zoom}`} role="img" aria-label="Directed transaction graph. Select nodes to inspect reported connections."><defs><marker id="flow-arrow" markerWidth="7" markerHeight="7" refX="19" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#76bba6" /></marker></defs>{transfers.slice(0, 120).map((t, i) => { const a = positions.get(t.from), b = positions.get(t.to); if (!a || !b || t.from === t.to) return null; return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} markerEnd="url(#flow-arrow)"><title>{t.amount} {t.asset} · {t.hash}</title></line>; })}{nodes.map((node, i) => { const p = positions.get(node)!, tx = node.startsWith('tx:'); return <g key={node} className={`flow-node ${i === 0 ? 'root' : ''} ${tx ? 'transaction' : ''} ${selected === node ? 'selected' : ''}`} transform={`translate(${p.x},${p.y})`} role="button" tabIndex={0} aria-label={`Inspect ${tx ? 'transaction' : 'wallet'} ${node}`} onClick={() => onSelect(node)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(node); } }}><circle r={i === 0 ? 23 : 16} /><text y="4" textAnchor="middle">{tx ? 'TX' : 'W'}</text><text y="36" textAnchor="middle" className="node-label">{short(node, 6)}</text><title>{node}</title></g>; })}</svg><p>{nodes.length} nodes shown · arrows follow reported transfer direction{nodes.length >= 24 ? ' · graph limited to 24 nodes' : ''}</p></div>;
}
export default function Crypto({ config, onSave }: { config: Row | null; onSave: () => void }) {
  const [chain, setChain] = useMemoryState('crypto:chain', 'bitcoin'), [wallet, setWallet] = useMemoryState('crypto:wallet', ''), [root, setRoot] = useMemoryState('crypto:root', ''), [live, setLive] = useMemoryState<Row[]>('crypto:live', []), [lookups, setLookups] = useMemoryState<Row[]>('crypto:lookups', []), [start, setStart] = useMemoryState('crypto:start', ''), [end, setEnd] = useMemoryState('crypto:end', ''), [selected, setSelected] = useMemoryState('crypto:selected', ''), [query, setQuery] = useMemoryState('crypto:filter', ''), [connectedOnly, setConnectedOnly] = useState(false);
  const imported = useData<Row[]>('/records/crypto', []), task = useTask('crypto');
  const chainConfig = config?.chains.find((c: Row) => c.id === chain);
  const chainNames = [...new Set([...(config?.chains.map((c: Row) => c.id) || ['bitcoin']), ...imported.data.map(t => t.chain)])];
  const transfers = useMemo(() => {
    const unique = new Map<string, Row>();
    for (const t of [...imported.data.filter(t => t.chain === chain), ...live]) unique.set(`${t.chain}:${t.hash}:${t.from}:${t.to}:${t.id || ''}`, t);
    return [...unique.values()].filter(t => (!start || Date.parse(t.timestamp) >= new Date(start).getTime()) && (!end || Date.parse(t.timestamp) <= new Date(end).getTime())).sort((a, b) => Date.parse(b.timestamp) - Date.parse(a.timestamp));
  }, [imported.data, chain, live, start, end]);
  const ledger = transfers.filter(t => `${t.from} ${t.to} ${t.hash} ${t.asset} ${t.source}`.toLowerCase().includes(query.toLowerCase()) && (!connectedOnly || !selected || t.from === selected || t.to === selected));
  async function trace(value: string, expand = false) {
    if (task.busy) return;
    const result = await task.run(() => api('/crypto', { chain, wallet: value }));
    if (result) { setRoot(expand ? root || value : value); setWallet(value); setSelected(value); setLive(old => expand ? [...old, ...result.transfers] : result.transfers); setLookups(old => expand ? [...old, result] : [result]); }
  }
  return <><PageTitle title="Crypto Tracing" description="Follow reported transfers, inspect wallet connections, and expand the fund flow." actions={<Importer module="crypto" label="Import transfers" onImport={imported.refresh} />} /><form className="search-form" onSubmit={e => { e.preventDefault(); void trace(wallet.trim()); }}><select aria-label="Blockchain" value={chain} onChange={e => { setChain(e.target.value); setLive([]); setLookups([]); setRoot(''); setSelected(''); task.setData(null); }}>{chainNames.map(id => <option key={id} value={id}>{config?.chains.find((c: Row) => c.id === id)?.name || id}</option>)}</select><label className="search-input"><Search size={17} /><span className="sr-only">Wallet address</span><input required value={wallet} onChange={e => setWallet(e.target.value)} placeholder={chain === 'bitcoin' ? 'Bitcoin mainnet wallet address' : 'Wallet address on the selected chain'} /></label><button className="button primary" disabled={task.busy}><GitBranch size={16} />{task.busy ? 'Tracing…' : 'Trace wallet'}</button></form><Notice>{chainConfig?.access === 'public' ? 'Bitcoin uses the public mempool.space API. Only the latest transaction page is retrieved.' : chainConfig?.access === 'provider' ? `Live EVM lookup ${config?.providers?.blockscout ? 'is configured' : 'requires BLOCKSCOUT_API_KEY'}. Native transactions only; chain availability depends on the provider.` : 'This chain supports imported transfer records.'} Imports work across all 24 listed chains and additional named chains.</Notice>{(task.error || imported.error) && <Notice tone="error">{task.error || imported.error}</Notice>}
    <section className="standalone-panel"><div className="row between wrap"><h2>Fund flow graph</h2><div className="row wrap"><label className="date-filter">From<input type="datetime-local" value={start} onChange={e => setStart(e.target.value)} /></label><label className="date-filter">To<input type="datetime-local" value={end} onChange={e => setEnd(e.target.value)} /></label>{transfers.length > 0 && <><ExportButton filename="wallet-flow.json" value={{ chain, root, transfers, lookups }} /><SaveButton module="crypto" key={`${chain}-${transfers.length}-${start}-${end}`} title={`Wallet flow · ${root ? short(root) : chain}`} source="Explorer APIs / imported transfers" payload={{ chain, root, transfers, lookups: lookups.map(({ transfers, ...lookup }) => lookup), timeWindow: { start, end } }} onSave={onSave} /></>}</div></div>{start && end && start > end && <Notice tone="warning">The start time is after the end time. Adjust the date range to see transfers.</Notice>}{transfers.length ? <FlowGraph transfers={transfers} root={root || transfers[0].from} selected={selected} onSelect={setSelected} /> : <Empty title="No transfers in this view">Trace a wallet using a connected provider, import an explorer export, or widen the time window.</Empty>}{selected && <div className="flow-inspector"><div><span className="tag">{selected.startsWith('tx:') ? 'Transaction' : 'Wallet'}</span><p><code>{selected}</code></p><p>{transfers.filter(t => t.to === selected).length} incoming · {transfers.filter(t => t.from === selected).length} outgoing edges in this view</p></div><div className="row wrap">{!selected.startsWith('tx:') && ['public', 'provider'].includes(chainConfig?.access) && <button className="button small" disabled={task.busy} onClick={() => void trace(selected, true)}><Plus size={14} />Expand wallet history</button>}<button className="button small" onClick={() => setConnectedOnly(v => !v)} aria-pressed={connectedOnly}>{connectedOnly ? 'Show all transfers' : 'Filter to connections'}</button><button className="icon-button" aria-label="Close wallet inspection" onClick={() => { setSelected(''); setConnectedOnly(false); }}><X size={15} /></button></div></div>}{lookups.map((l, i) => <div key={i}><Source name={l.chain === 'bitcoin' ? 'mempool.space' : 'Blockscout'} url={l.source} retrievedAt={l.retrievedAt} /><p className="muted">{l.caveat}</p></div>)}</section>
    {transfers.length > 0 && <section className="standalone-panel"><div className="flow-tools"><h2>Transfer ledger <span className="count">{ledger.length}</span></h2><input className="filter-input" aria-label="Filter transfer ledger" placeholder="Filter wallets, transaction hashes, or assets…" value={query} onChange={e => setQuery(e.target.value)} /></div><p className="muted">Select an address to inspect its connections, then expand its public history. Transaction nodes retain Bitcoin's multiple-input and multiple-output structure. Owner labels are not inferred.</p>{ledger.length ? <div className="table-wrap"><table><thead><tr><th>Time</th><th>From</th><th>To</th><th>Amount</th><th>Source</th></tr></thead><tbody>{ledger.slice(0, 500).map((t, i) => <tr key={i}><td>{time(t.timestamp)}{t.confirmed === false && <small>Unconfirmed · retrieval time</small>}</td><td className="mono" title={t.from}><button className="ledger-wallet" onClick={() => setSelected(t.from)}>{short(t.from)}</button></td><td className="mono" title={t.to}><button className="ledger-wallet" onClick={() => setSelected(t.to)}>{short(t.to)}</button></td><td className="mono">{t.amount} {t.asset}</td><td><External href={t.url}>{t.source}</External><small>{t.edgeType || ''}</small></td></tr>)}</tbody></table></div> : <Empty title="No matching transfers">Clear the ledger search or show all wallet connections.</Empty>}{ledger.length > 500 && <p>First 500 transfers displayed. Export includes the full time-filtered ledger.</p>}</section>}</>;
}
