import { useState, useEffect } from 'react';
import { Download, NotebookPen, Trash2 } from 'lucide-react';
import { Empty, JsonView, Notice, PageTitle, Source } from '../components/common';
import { api, download, useData, useMemoryState, type Row } from '../lib/api';
function EvidenceEntry({ item, refresh, highlight }: { item: Row; refresh: () => void; highlight: boolean }) {
  const [notes, setNotes] = useState(item.notes), [status, setStatus] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  return <article id={`evidence-${item.id}`} className={`evidence-entry ${highlight ? "highlight" : ""}`}><div className="row between wrap"><div><span className="tag">{item.module}</span><h2>{item.title}</h2><Source name={item.source} retrievedAt={item.created} /></div><div className="row"><button className="button small" onClick={() => download(`evidence-${item.id}.json`, item)}><Download size={14} />Export</button><button className="icon-button danger" aria-label={`Delete evidence ${item.title}`} onClick={async () => { try { await api(`/evidence/${item.id}`, undefined, 'DELETE'); refresh(); } catch (e) { setError((e as Error).message); } }}><Trash2 size={15} /></button></div></div>{item.notes && <p className="evidence-notes-preview">{String(item.notes).slice(0, 260)}{item.notes.length > 260 ? "…" : ""}</p>}<details open={highlight || undefined}><summary>Evidence and notes</summary><JsonView value={item.payload} /><label>Research notes<textarea rows={4} value={notes} onChange={e => { setNotes(e.target.value); setStatus(''); }} placeholder="Add context, uncertainties, or follow-up questions…" maxLength={10000} /></label><div className="row"><button className="button small" disabled={busy || notes === item.notes} onClick={async () => { setBusy(true); setError(''); try { await api(`/evidence/${item.id}`, { notes }, 'PATCH'); setStatus('Notes saved'); refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{busy ? 'Saving…' : 'Save notes'}</button><span role="status">{status}</span></div></details>{error && <Notice tone="error">{error}</Notice>}</article>;
}
export default function Evidence({ onRefresh }: { onRefresh: () => void }) {
  const { data, error, refresh, busy } = useData<Row[]>('/evidence', []); const [filter, setFilter] = useMemoryState('evidence:filter', ''), [module, setModule] = useMemoryState('evidence:module', 'All modules'), [sort, setSort] = useMemoryState('evidence:sort', 'Newest first'), [highlight, setHighlight] = useState('');
  useEffect(() => { const read = () => { const entry = new URLSearchParams(location.hash.split('?')[1]).get('entry'); setHighlight(entry || ''); if (entry) { setFilter(''); setModule('All modules'); } }; read(); window.addEventListener('hashchange', read); return () => window.removeEventListener('hashchange', read); }, []);
  useEffect(() => { if (highlight && data.length) document.getElementById(`evidence-${highlight}`)?.scrollIntoView({ block: 'center', behavior: 'auto' }); }, [highlight, data]);
  const entries = data.filter(e => `${e.title} ${e.source} ${e.module} ${e.notes}`.toLowerCase().includes(filter.toLowerCase()) && (module === 'All modules' || module === e.module)).sort((a, b) => sort === 'Title A–Z' ? a.title.localeCompare(b.title) : (sort === 'Oldest first' ? 1 : -1) * (Date.parse(a.created) - Date.parse(b.created)));
  return <><PageTitle title="Evidence notebook" description="Saved findings, source records, and your notes across every research module." actions={<a className="button" href="/api/export" download><Download size={16} />Export workspace</a>} /><div className="notebook-toolbar"><input aria-label="Filter saved evidence" className="filter-input" placeholder="Search titles, sources, modules, or notes…" value={filter} onChange={e => setFilter(e.target.value)} /><select aria-label="Evidence module" value={module} onChange={e => setModule(e.target.value)}><option>All modules</option>{[...new Set<string>(data.map(e => e.module))].sort().map(m => <option key={m}>{m}</option>)}</select><select aria-label="Evidence sort order" value={sort} onChange={e => setSort(e.target.value)}>{["Newest first", "Oldest first", "Title A–Z"].map(s => <option key={s}>{s}</option>)}</select><span>{entries.length} of {data.length} saved findings</span></div>{error && <Notice tone="error">{error}</Notice>}{entries.length ? <div className="evidence-list">{entries.map(item => <EvidenceEntry key={item.id} item={item} highlight={highlight === item.id} refresh={() => { refresh(); onRefresh(); }} />)}</div> : <Empty title={busy ? 'Loading saved evidence' : data.length ? 'No findings match these filters' : 'Your research starts here'}>Use “Save evidence” in any module to keep the underlying records and add notes. Workspace export includes imports, evidence, favorites, and consented visits.</Empty>}<Notice><NotebookPen size={16} />Stored locally in SQLite. Exported findings preserve reported source and retrieval time; saving them does not establish accuracy.</Notice></>;
}
