import { useState } from 'react';
import { Network } from 'lucide-react';
import { Empty, JsonView, Notice, PageTitle, SaveButton, Source, ExportButton } from '../components/common';
import { api, useTask, useMemoryState, type Row } from '../lib/api';
export default function NetScan({ config, onSave }: { config: Row | null; onSave: () => void }) {
  const [target, setTarget] = useMemoryState('netscan:target', 'localhost'), [ports, setPorts] = useMemoryState('netscan:ports', '80,443,8787'), [mode, setMode] = useMemoryState('netscan:mode', 'dns'), [authorized, setAuthorized] = useState(false); const task = useTask(`netscan:${mode}`);
  return <><PageTitle title="NetScan" description="Resolve domain infrastructure and test services within your authorized scope." /><div className="network-layout"><section className="standalone-panel"><div className="segmented wide">{[['dns', 'DNS records'], ['certificates', 'Subdomain leads'], ['netscan', 'Active scan']].map(([id, name]) => <button key={id} className={mode === id ? 'active' : ''} onClick={() => { setMode(id); }}>{name}</button>)}</div><form className="stack-form" onSubmit={e => { e.preventDefault(); void task.run(() => api(`/${mode}`, { target, ports, authorized })); }}><label>Target<input value={target} onChange={e => setTarget(e.target.value)} placeholder={mode === 'netscan' ? 'IP, domain, /28–/32 range, or .onion' : 'Domain name or IP address'} required /></label>{mode === 'netscan' && <><label>TCP ports<input value={ports} onChange={e => setPorts(e.target.value)} placeholder="80,443" required /><small>Up to 32 ports, 16 range addresses, and 8 concurrent connections.</small></label><label className="checkbox"><input type="checkbox" checked={authorized} onChange={e => setAuthorized(e.target.checked)} />I have permission to test the configured target.</label></>}<button className="button primary" disabled={task.busy || (mode === 'netscan' && !authorized)}><Network size={16} />{task.busy ? 'Checking…' : mode === 'dns' ? 'Resolve DNS' : mode === 'certificates' ? 'Find certificate names' : 'Run bounded scan'}</button></form>{task.error && <Notice tone="error">{task.error}</Notice>}<p className="muted">{mode === 'dns' ? 'Uses the system DNS resolver. Missing and unavailable records are distinguished.' : mode === 'certificates' ? 'Uses crt.sh certificate transparency. Historical certificate names are leads, not confirmed active subdomains.' : 'Only SCAN_ALLOWLIST targets are reachable. Tor v3 addresses need a valid checksum and a running local SOCKS proxy.'}</p></section><section className="scope-panel"><h2>Configured scan scope</h2><p>Active probes are restricted by the local server.</p><div className="scope-list">{config?.scopes?.map((s: string) => <code key={s}>{s}</code>)}</div><p className="muted">Edit SCAN_ALLOWLIST in .env and restart to add authorized targets. CIDRs belong in this configuration; a checkbox alone cannot expand the scope.</p></section></div>
    {task.data ? <section className="standalone-panel"><div className="row between"><h2>{task.data.target || task.data.host}</h2><ExportButton filename="network-research.json" value={task.data} /><SaveButton key={task.data.retrievedAt} module="netscan" title={`Network research · ${task.data.target || task.data.host}`} source={task.data.source} payload={task.data} onSave={onSave} /></div><Source name={task.data.source} retrievedAt={task.data.retrievedAt} />{task.data.caveat && <Notice tone="warning">{task.data.caveat}</Notice>}{task.data.results && <div className="table-wrap"><table><thead><tr><th>Address</th><th>Port</th><th>State</th><th>Observation</th><th>Time</th></tr></thead><tbody>{task.data.results.map((r: Row) => <tr key={`${r.host}:${r.port}`}><td className="mono">{r.host}</td><td className="mono">{r.port}</td><td><span className={`tag ${r.state === 'open' ? 'positive' : ''}`}>{r.state}</span></td><td>{r.detail}{r.certificate && <details><summary>TLS certificate</summary><JsonView value={r.certificate} /></details>}</td><td>{r.elapsedMs} ms</td></tr>)}</tbody></table></div>}{task.data.records && <div className="dns-records">{Object.entries(task.data.records).map(([type, value]) => <article key={type}><div className="row"><h3>{type}</h3><span className="tag">{(value as Row).status}</span></div><JsonView value={(value as Row).values} />{(value as Row).reason && <p className="muted">{(value as Row).reason}</p>}</article>)}</div>}{task.data.names && <><p>{task.data.names.length} certificate names returned, capped at 500.</p><div className="name-list">{task.data.names.map((n: string) => <code key={n}>{n}</code>)}</div></>}</section> : !task.busy && <Empty title="Inspect a domain or local service">Start with DNS, review certificate names, or run a bounded scan on an allowed target.</Empty>}</>;
}
