import { useState } from 'react';
import { AtSign, ShieldCheck, Download } from 'lucide-react';
import { Empty, External, JsonView, Notice, PageTitle, SaveButton, SearchForm, Source } from '../components/common';
import { api, download, useTask, useMemoryState } from '../lib/api';
export default function Username({ config, onSave }: { config: any; onSave: () => void }) {
  const [filter, setFilter] = useMemoryState('username:filter', 'All sources');
  const task = useTask('username'), breach = useTask('username:breaches'); const [email, setEmail] = useState(''), [authorized, setAuthorized] = useState(false);
  return <><PageTitle title="Username OSINT" description="Check public profiles, compare leads, and keep identity uncertainty visible." /><SearchForm cacheKey="username:input" label="Username" placeholder="Enter a handle, without @" busy={task.busy} button="Check public sources" onSubmit={handle => void task.run(() => api('/username', { handle }))} />{task.error && <Notice tone="error">{task.error}</Notice>}{!task.data && !task.busy && <Empty title="Start with a public handle">GitHub, GitLab, and Hacker News use public APIs. Other platforms offer links for manual review.</Empty>}{task.data && <><div className="result-summary"><span><AtSign size={18} /><strong>{task.data!.handle}</strong> · {task.data!.results.filter((r: any) => r.status === 'found').length} public profile matches</span><button className="button small" onClick={() => download(`username-${task.data!.handle}.json`, task.data)}><Download size={14} />Export</button><SaveButton key={task.data!.retrievedAt} module="username" title={`Username lookup · ${task.data!.handle}`} source="Public profile APIs" payload={task.data} onSave={onSave} /></div><Notice tone="warning">{task.data!.caveat}</Notice><div className="result-filter-bar">{["All sources", "Public matches", "Manual review", "No match / unavailable"].map(name => <button key={name} className={filter === name ? "active" : ""} onClick={() => setFilter(name)} aria-pressed={filter === name}>{name}<span>{task.data!.results.filter((r: any) => name === "All sources" || (name === "Public matches" ? r.status === "found" : name === "Manual review" ? r.status === "not_searched" : !["found", "not_searched"].includes(r.status))).length}</span></button>)}</div><div className="profile-list">{task.data!.results.filter((r: any) => filter === "All sources" || (filter === "Public matches" ? r.status === "found" : filter === "Manual review" ? r.status === "not_searched" : !["found", "not_searched"].includes(r.status))).map((r: any) => <article key={r.platform} className="profile-row"><div className="platform-name"><AtSign size={18} /><h2>{r.platform}</h2><span className={`tag ${r.status === 'found' ? 'positive' : ''}`}>{r.status.replaceAll('_', ' ')}</span></div><div>{r.profile ? <><h3>{r.profile.name}</h3>{r.profile.bio && <p>{String(r.profile.bio).replace(/<[^>]*>/g, '')}</p>}<dl>{Object.entries(r.profile).filter(([k, v]) => !['name', 'bio'].includes(k) && v !== null && v !== '').map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl></> : <p className="muted">{r.error || 'No public account returned by this source.'}</p>}<Source name={r.platform} url={r.source} retrievedAt={r.retrievedAt} /></div><External href={r.url}>{r.status === 'found' ? 'View profile' : 'Review source'}</External></article>)}</div></>}
    <section className="standalone-panel"><div className="row"><ShieldCheck size={20} /><h2>Account breach audit</h2><span className="tag">{config?.providers?.hibp ? 'Provider configured' : 'Provider key required'}</span></div><p>Have I Been Pwned account lookup for accounts you own or are authorized to audit. Breach content, passwords, and leaked records are not retrieved.</p><form onSubmit={e => { e.preventDefault(); void breach.run(() => api('/breaches', { email, authorized })); }} className="stack-form"><label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="you@example.org" /></label><label className="checkbox"><input type="checkbox" checked={authorized} onChange={e => setAuthorized(e.target.checked)} />I own this account or have permission to audit it.</label><button className="button" disabled={!authorized || breach.busy || !config?.providers?.hibp}>{breach.busy ? 'Checking…' : 'Check account breaches'}</button></form>{!config?.providers?.hibp && <p className="muted">Add HIBP_API_KEY to .env and restart the server to enable this audit.</p>}{breach.error && <Notice tone="error">{breach.error}</Notice>}{breach.data && <><p>{breach.data.breaches.length} breaches returned.</p><JsonView value={breach.data.breaches} /><SaveButton key={breach.data.retrievedAt} module="username" title={`Breach audit · ${email}`} source="Have I Been Pwned" payload={breach.data} onSave={onSave} /></>}</section></>;
}
