import { useEffect, useMemo, useState } from 'react';
import { RefreshCw, Radio, MapPin, ArrowUpRight, Camera } from 'lucide-react';
import Globe from '../components/Globe';
import { Busy, Empty, External, Importer, Notice, PageTitle, SaveButton, Source } from '../components/common';
import { api, time, useData, useMemoryState, nearbyCameraRoute, type Row } from '../lib/api';
export default function Watchtower({ onSave }: { onSave: () => void }) {
  const { data, busy, error, refresh, setData } = useData<Row>('/watchtower', { feeds: [], events: [] });
  const [selected, setSelected] = useMemoryState('watchtower:selected', ''), [category, setCategory] = useMemoryState('watchtower:category', 'All events'), [query, setQuery] = useMemoryState('watchtower:query', ''), [refreshing, setRefreshing] = useState(false), [refreshError, setRefreshError] = useState('');
  const [space, setSpace] = useState<Row | null>(null), [spaceError, setSpaceError] = useState('');
  useEffect(() => { const timer = setInterval(refresh, 300000); const controller = new AbortController(); api('/space-weather', undefined, 'GET', controller.signal).then(setSpace).catch(e => { if (!controller.signal.aborted) setSpaceError(e.message); }); return () => { clearInterval(timer); controller.abort(); }; }, [refresh]);
  const categories = [...new Set<string>(data.events.map((e: Row) => e.category))];
  const events = useMemo(() => data.events.filter((e: Row) => (category === 'All events' || e.category === category) && `${e.title} ${e.source}`.toLowerCase().includes(query.toLowerCase())).sort((a: Row, b: Row) => Date.parse(b.timestamp) - Date.parse(a.timestamp)), [data.events, category, query]);
  const item = data.events.find((e: Row) => e.id === selected);
  const readyFeeds = data.feeds.filter((f: Row) => f.status === 'ready').length;
  return <><PageTitle title="Watchtower" description="Natural hazards and public signals, in one situational picture." actions={<><Importer module="watchtower" onImport={refresh} /><button className="button" disabled={busy || refreshing} onClick={async () => { setRefreshing(true); setRefreshError(''); try { setData(await api('/watchtower?refresh=1')); } catch (e) { setRefreshError((e as Error).message); } finally { setRefreshing(false); } }}><RefreshCw size={16} className={refreshing ? 'spin' : ''} />Refresh feeds</button></>} />
    {(error || refreshError) && <Notice tone="error">{error || refreshError}</Notice>}
    <div className="map-workspace"><section className="map-main"><div className="map-toolbar"><div className="feed-indicator"><Radio size={16} /><strong>{readyFeeds ? 'Public feeds connected' : busy ? 'Connecting public feeds' : 'Feeds unavailable'}</strong><span>{readyFeeds} of {data.feeds.length || 2}</span></div><select aria-label="Event category" value={category} onChange={e => setCategory(e.target.value)}><option>All events</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div><Globe points={events} selected={selected} onSelect={setSelected} /><div className="map-bottom"><span className="legend amber">Earthquakes</span><span className="legend mint">Natural events</span><span>Auto-refresh every 5 minutes</span></div></section>
    <aside className="inspector"><div className="inspector-heading"><h2>{item ? 'Event details' : 'Event feed'}</h2><span className="count">{events.length}</span></div>{item ? <div className="detail"><button className="text-button" onClick={() => setSelected('')}>Back to events</button><span className="tag">{item.category}</span><h2>{item.title}</h2>{item.magnitude !== undefined && <div className="measurement">{item.magnitude}<span>magnitude</span></div>}<p className="coordinate"><MapPin size={15} />{item.lat.toFixed(4)}, {item.lon.toFixed(4)}</p><dl><dt>Event time</dt><dd>{time(item.timestamp)}</dd>{item.depth !== undefined && <><dt>Depth</dt><dd>{item.depth} km</dd></>}</dl><Source name={item.source} retrievedAt={item.retrievedAt || item.importedAt} url={item.url} />{item.stale && <Notice tone="warning">Cached data. The latest retrieval failed.</Notice>}<SaveButton key={item.id} module="watchtower" title={item.title} source={item.source} payload={item} onSave={onSave} /><External href={item.url}>Open source report</External><a className="button small" href={nearbyCameraRoute(item.lat, item.lon)}><Camera size={15} />Explore nearby cameras</a></div> : <><input className="filter-input" aria-label="Filter events" placeholder="Filter events or sources…" value={query} onChange={e => setQuery(e.target.value)} />{busy ? <Busy label="Retrieving event feeds" /> : !events.length ? <Empty title="No events in this view">Try a different filter, refresh the feeds, or import your own geolocated events.</Empty> : <div className="event-list">{events.slice(0, 200).map((e: Row) => <button key={e.id} className="event-row" onClick={() => setSelected(e.id)}><span className={`event-marker ${e.category === 'Earthquake' ? 'amber' : 'mint'}`}>{e.magnitude !== undefined ? `M${e.magnitude.toFixed(1)}` : <Radio size={16} />}</span><span><strong>{e.title}</strong><small>{e.category} · {e.source}{e.stale ? ' · cached' : ''}</small><time>{time(e.timestamp)}</time></span><ArrowUpRight size={14} /></button>)}</div>}</> }</aside></div>
    <section className="source-health"><div><h2>Source coverage</h2><p>Event locations are source-reported. Live aviation, maritime, and threat feeds need separate providers or imports.</p></div><div className="feed-status-list">{data.feeds.map((f: Row) => <div key={f.name}><span className={`status-dot ${f.status}`} /><strong>{f.name}</strong><span>{f.status === 'ready' ? `Retrieved ${time(f.retrievedAt)}` : `${f.status}: ${f.error}`}</span><External href={f.url}>Feed</External></div>)}{space && <div><span className="status-dot ready" /><strong>NOAA space weather</strong><span>Latest planetary K index: {space.readings.at(-1)?.Kp ?? 'unavailable'} · {space.readings.at(-1)?.time_tag} UTC</span><External href={space.source}>Feed</External></div>}{spaceError && <div><span className="status-dot unavailable" /><strong>NOAA space weather</strong><span>{spaceError}</span></div>}</div></section></>;
}
